FORMAT: 1A

# Agenda API

## Group User

### Agenda-User Get All User Api [GET /api/agenda/user]

+ Response 200 (application/json)

  + Body

    {
      "is_login_api":"/api/agenda/user/login{?userid}",
      "login_aoi":"/api/agenda/user/login",
      "register_api":"/api/agenda/user/register",
      "logout_api":"/api/agenda/user/logout",
      "delete_api":"/api/agenda/user/self",
      "query_api":"/api/agenda/users"
    }

+ Response 400 (application/json)

  + Body

  {
    "message": "get user api fail",
    "data": {
      "error":"error_message"
    }
  }

### Agenda-User Is Login [Get /api/agenda/user/login{?userid}]

+ Parameters

  + userid (string, required)

+ Response 200 (application/json)

  + Body

    {
      "username": "test"
    }

  + Response 400 (application/json)

    + Body

      {
        "message":"no login"
      }

### Agenda-User Login [POST /api/agenda/user/login]

+ Request(application/json)

  + Body

    {
      "username": "test",
      "password": "12345678"
    }

+ Response 200 (application/json)

  + Body

    {
      "message":"login success"
    }

+ Response 400 (application/json)

  + Body

    {
      "message": "login fail",
      "data": {
        "error":"error_message"
      }
    }

### Agenda-User Register [POST /api/agenda/user/register]

+ Request (application/json)

  + Body

    {
      "username":"test",
      "passqord":"12345678",
      "email":"test@163.com",
      "phone":"12345679101"
    }

+ Response 200 (application/json)

  + Header

    + Location: /api/agenda/user/login

  + Body

    {
      "message":"register success"
    }

+ Response 400 (application/json)

  + Body

    {
      "message": "register fail",
      "data": {
        "error":"error_message"
      }
    }

### Agenda-User Logout [POST /api/agenda/user/logout]

+ Response 200 (application/json)

    + Header

      + Location: /api/agenda/login

    + Response

      + Body

        {
          "message":"logout success"
        }

+ Response 400 (application/json)

  + Body

    {
      "message": "fail",
      "data": {
        "error":"error_message"
      }
    }

### Agenda-User Show Users [GET /api/agenda/users]

+ Response 200 (application/json)

  + Body

    {
      "message":"query users success",
      "data": {
        "uselist":{
          "test1":{
            "username":"test1",
            "email":"test1@163.com",
            "phone":"12345679101"
          },
          "test2":{
            "username":"test2",
            "email":"test2@163.com",
            "phone":"12345679102"
          },
          "test3":{
            "username":"test3",
            "email":"test3@163.com",
            "phone":"12345679103"
          },
        }
      }
    }

+ Response 400 (application/json)

  + Body

    {
      "message": "query users fail",
      "data": {
        "error":"error_message"
      }
    }

### Agenda-User Delete [DELETE /api/agenda/user/self]

+ Response 200 (application/json)

  + Header

    Location: /api/agenda/user/login

  + Response

    + Body

      {
        "message":"delete success"
      }

+ Response 400 (application/json)

  + Body

    {
      "message": "fail",
      "data": {
        "error":"error_message"
      }
    }


## Group Meeting

### Agenda-Meeting Get All Meeting-Api [GET /api/agenda/meeting]

+ Response 200 (application/json)

  + Body

    {
      "create_meeting":"/api/agenda/meeting",
      "add_participators":"/api/agenda/meeting/{title}/participators",
      "delete_participators":"/api/agenda/meeting/{title}/participators",
      "qurey_meetings":"/api/agenda/meeting{?starttime, endtime}",
      "cancel_meeting":"/api/agenda/meeting/sponser/{title}",
      "quit_meeting":"/api/agenda/meeting/participator/{title}",
      "delete_allmeeting":"/api/agenda/meeting/sponsers/all"
    }

  + Response 400 (application/json)

    + Body

    {
      "message": "get meeting api fail",
      "data": {
        "error":"error_message"
      }
    }


### Agenda-Meeting Create [POST /api/agenda/meeting]

+ Request (application/json)

  + Body

    {
      "title":"test_title",
      "participators":["test1_participator1", "test1_participator2", "test1_participator3"],
      "starttime":"2017-12-10 10:00:00",
      "endtime":"2017-12-11 11:00:00"
    }

+ Response 200 (application/json)

  + Body
    {
      "message":"success"
    }

+ Response 400 (application/json)
    {
      "message": "fail",
      "data": {
        "error":"error_message"
      }
    }

### Agenda-Meeting Add Participators [POST /api/agenda/meeting/{title}/participators]

+ Request (application/json)

  + Body

    {
      "participators":["test_participator1", "test_participator2", "test_participator3"]
    }

+ Response 200 (application/json)

  + Body

    {
      "message":"add participators success"
    }

+ Response 400 (application/json)

  + Body

    {
      "message": "add participators fail",
      "data": {
        "error":"error_message"
      }
    }

### Agenda-Meeting Delete Participators [DELETE /api/agenda/meeting/{title}/participators]

+ Request (application/json)

  + Body

    {
      "participators":["test_participator1", "test_participator2", "test_participator3"]
    }

+ Response 200 (application/json)

  + Body

    {
      "message":"delete participators success"
    }

+ Response 400 (application/json)

  + Body

    {
      "message": "deltete participators fail",
      "data": {
        "error":"error_message"
      }
    }

### Agenda-Meeting Query [GET /api/agenda/meeting{?starttime, endtime}]

+ Parameters
    + starttime (string, required)
    + endtime (string, required)

+ Response 200 (application/json)

  + Body

    {
      "message":"query meetings success",
      "data": {
        "meetinglist":{
          "test_title1": {
            "title":"test_title1",
            "sponser":"tset_sponser1",
            "participators":["test1_participator", "test2_participator", "test3_participator"],
            "starttime":"2017-12-10 10:00:00",
            "endtime":"2017-12-10 11:00:00"
          },
          "test_title2": {
            "title":"test_title2",
            "sponser":"tset_sponser2",
            "participators":["test1_participator", "test2_participator", "test3_participator"],
            "starttime":"2017-12-11 10:00:00",
            "endtime":"2017-12-11 11:00:00"
          },
          "test_title3": {
            "title":"test_title3",
            "sponser":"tset_sponser3",
            "participators":["test1_participator", "test2_participator", "test3_participator"],
            "starttime":"2017-12-12 10:00:00",
            "endtime":"2017-12-12 11:00:00"
          }
        }
      }
    }

+ Response 400 (application/json)

  + Body

    {
      "message": "query meetings fail",
      "data": {
        "error":"error_message"
      }
    }

    ### Agenda-Meeting Cancel [DELETE /api/agenda/meeting/sponser/{title}]

    + Response 200 (application/json)

      + Body

        {
          "message":"cancel meeting success"
        }

    + Response 400 (application/json)

      + Body

        {
          "message": "cancel meeting fail",
          "data": {
            "error":"error_message"
          }
        }

### Agenda-Meeting Quit [DELETE /api/agenda/meeting/participator/{title}]

+ Response 200 (application/json)

  + Body

    {
      "message":"quit meeting success"
    }

+ Response 400 (application/json)

  + Body

    {
      "message": "quit meeting fail",
      "data": {
        "error":"error_message"
      }
    }

### Agenda-Meeting Delete All [DELETE /api/agenda/meeting/sponsers/all]

+ Response 200 (application/json)

  + Body

    {
      "message":"delete all meetings success"
    }

+ Response 400 (application/json)

  + Body

    {
      "message": "deltet all meetings fail",
      "data": {
        "error":"error_message"
      }
    }
